#*******************************************************************************
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corp. 2021. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
#*******************************************************************************
all:
  hosts:
    zos_host:
      ansible_host: 128.168.133.93
      ansible_user: ibmuser
      ansible_password: sys1 
      ansible_ssh_port: 9222
